updated README and many changes in scripts, improving robustness

diff --git a/scripts/createLogs b/scripts/createLogs
--- a/scripts/createLogs
+++ b/scripts/createLogs
@@ -1,82 +1,118 @@
 #!/bin/bash
 HOME_DIR="/home/aide/aide"
-
-for client in `ls ${HOME_DIR}/clients`
-do
-    echo "Client ${client}:"
-	count=`ls ${HOME_DIR}/spool | grep -P "^${client}-[0-9]{10}" | wc -l`
-	if [ "$count" -ge "2" ]; then
-	
-		newer=`ls ${HOME_DIR}/spool | grep -P "^${client}-[0-9]{10}" | sort -r| sed -n '1p'`
-		if [ -f "${HOME_DIR}/clients/${client}/logs/${newer}" ]; then
-		  echo "   No newer version available. Aborting..."
-		  continue
+info () {
+	echo -e "   $1"
+}
+ok () {
+	echo -e "   [\e[32mOK\e[0m] $1"
+}
+warrning () {
+	echo -e "   [\e[93mWARRNING\e[0m] $1"
+}
+error () {
+	echo -e "   [\e[31mERROR\e[0m] $1"
+	exit ${2}
+}
+if ! ls ${HOME_DIR}/clients > /dev/null; then
+	info "No registered clients."
+fi
+for client in $(ls ${HOME_DIR}/clients); do
+	echo "Client ${client}:"
+	COUNT="$(ls ${HOME_DIR}/spool | grep -P "^${client}-[0-9]{10}" | wc -l)"
+	if [ ${COUNT} -ge 2 ]; then
+		NEWER="$(ls ${HOME_DIR}/spool | grep -P "^${client}-[0-9]{10}" | sort -r | sed -n '1p')"
+		if [ -f "${HOME_DIR}/clients/${client}/logs/${NEWER}" ]; then
+			info "No new version available for this client."
+			continue
 		else
-		  echo "   New version has been found: ${newer}"
+			info "New version has been found: ${NEWER}"
 		fi
-		
-		older=`ls ${HOME_DIR}/spool | grep -P "^${client}-[0-9]{10}" | sort -r| sed -n '2p'`
-		echo "   Recent version has been found: ${older}"
-			
-		echo "   Setting up ${client}.conf for new version."
-			cat ${HOME_DIR}/conf/${client}.conf | 
-			sed -r "s|^(database=file:).*$|\1${HOME_DIR}/spool/${older}|" |
-			sed -r "s|^(database_new=file:).*$|\1${HOME_DIR}/spool/${newer}|" > /tmp/xxx
-			cat /tmp/xxx > ${HOME_DIR}/conf/${client}.conf
-			
-		echo "   Comparing databases. Please wait..."
+		OLDER=$(ls ${HOME_DIR}/spool | grep -P "^${client}-[0-9]{10}" | sort -r | sed -n '2p')
+		info "Recent version has been found: ${OLDER}"
+		info "Setting up conf file."
+		cat ${HOME_DIR}/conf/${client}.conf | sed -r "s|^(database=file:).*$|\1${HOME_DIR}/spool/${OLDER}|" | sed -r "s|^(database_new=file:).*$|\1${HOME_DIR}/spool/${NEWER}|" > /tmp/xxx
+		cat /tmp/xxx > ${HOME_DIR}/conf/${client}.conf
+		info "Comparing databases. Please wait..."
 		aide_error_log="${HOME_DIR}/logs/aide-`date +%s`"
-			/usr/sbin/aide -c ${HOME_DIR}/conf/${client}.conf --compare 1>${HOME_DIR}/clients/${client}/logs/${newer} 2>${aide_error_log}
-
-		if [ "$?" -lt "14" ]; then
-			echo -e "   [\e[32mOK\e[0m] OUTPUT HAS BEEN SAVED TO PROPER LOG FILE"
+		std_log="${HOME_DIR}/clients/${client}/logs/${NEWER}"
+		/usr/sbin/aide -c ${HOME_DIR}/conf/${client}.conf --compare 1>${std_log} 2>${aide_error_log}
+		if [ "$?" -lt 14 ]; then
+			ok "Output has been saved to proper log file."
 			if [ ! -s ${aide_error_log} ]; then
 				rm -f ${aide_error_log}      
 			fi
-		  else
-			echo -e "   [\e[31mERROR\e[0m] AIDE ERROR" 
-			exit 1
+			${HOME_DIR}/scripts/nagios.sh ${client} > /dev/null
+			if [ $? -eq 1 ]; then
+				BACKUP_COMMAND="${HOME_DIR}/scripts/backup.sh -h ${client} "
+				FILES_TO_CHANGE=$(awk 'BEGIN{FS=" ";ORS=" "}($0 ~ "^changed:"){print $2}' ${std_log})
+				FILES_TO_ADD=$(awk 'BEGIN{FS=" ";ORS=" "}($0 ~ "^added:"){print $2}' ${std_log})
+				FILES_TO_REMOVE=$(awk 'BEGIN{FS=" ";ORS=" "}($0 ~ "^removed:"){print $2}' ${std_log})
+				if [ ! -z "${FILES_TO_CHANGE}" ]; then
+					BACKUP_COMMAND+="-c ${FILES_TO_CHANGE}"
+				fi
+				if [ ! -z "${FILES_TO_ADD}" ]; then
+					BACKUP_COMMAND+="-c ${FILES_TO_ADD}"
+				fi
+				if [ ! -z "${FILES_TO_REMOVE}" ]; then
+					BACKUP_COMMAND+="-c ${FILES_TO_REMOVE}"
+				fi
+				eval ${BACKUP_COMMAND}
+				##improving logs by introducing differences, under construction, care of times
+				NEW_DUMP="$(ls ${HOME_DIR}/clients/${client}/backup | grep -P "^dump-[0-9]{10}.tar$" | sort -r | sed -n '1p')"
+				NEW_DUMP_PATH="${HOME_DIR}/clients/${client}"${NEW_DUMP}
+			fi
+		else
+			if [ ! -s ${std_log} ]; then
+				rm -f ${std_log}      
+			fi
+			error "Something went wrong during AIDE comparison. Check directory logs." 3
 		fi
 	else
-		echo -e "   [\e[93mWARRNING\e[0m] Not enough amount of versions has been provided."
+		warrning "Not enough amount of versions has been provided."
 	fi
 done
-
-echo "Cleaning:"
-echo "   Looking for wrong named files..."
-for d in `ls ${HOME_DIR}/spool | grep -vP ^.+-[0-9]{10}`; do
-  echo "      Removing ${d}"
-  rm -f ${HOME_DIR}/spool/${d}
+echo "Additional operations: "
+check=0
+for file in $(ls ${HOME_DIR}/spool | grep -vP ^.+-[0-9]{10}); do
+	info "   Removing trash file: ${file}"
+	rm -f ${HOME_DIR}/spool/${file}
+	check=1
 done
-echo "   Looking for unregistered clients..."
-list=""
-for d in `ls ${HOME_DIR}/clients`; do
-  list+=`ls ${HOME_DIR}/spool | grep "${d}-"`
+if [[ ${check} == 0 ]]; then
+	ok "No trash files in spool directory."
+fi
+check=0
+list_of_clients=""
+for client in $(ls ${HOME_DIR}/clients); do
+	list_of_clients+=$(ls ${HOME_DIR}/spool | grep "${client}-")
 done
-for d in `ls ${HOME_DIR}/spool`; do
-  if ! echo $list | grep ${d} > /dev/null; then 
-    echo "      Removing ${d}"
-    rm -f ${HOME_DIR}/spool/$d
-  fi
+for database in `ls ${HOME_DIR}/spool`; do
+	if ! echo ${list_of_clients} | grep ${database} > /dev/null; then 
+		info "   Removing unregistered client's database: ${database}"
+		rm -f ${HOME_DIR}/spool/${database}
+		check=1
+	fi
 done
-
-echo "   Looking for redundant databases..." 
-for z in `ls ${HOME_DIR}/clients`; do
-  for d in `ls ${HOME_DIR}/spool | grep -P ^${z}-[0-9]{10} | sort -r| sed -n '3,$p'`; do
-    echo "      Removing ${d}"
-    rm -f ${HOME_DIR}/spool/$d
-  done
+if [[ ${check} == 0 ]]; then
+	ok "No unregistered client's databases."
+fi
+check=0
+for client in $(ls ${HOME_DIR}/clients); do
+	for database in $(ls ${HOME_DIR}/spool | grep -P ^${client}-[0-9]{10} | sort -r | sed -n '3,$p'); do
+		info "   Removing redundant database: ${database}"
+		rm -f ${HOME_DIR}/spool/${database}
+		check=1
+	done
 done
-
-echo "Checking cron options..."
-if crontab -l 2>/dev/null | grep "0 \*/3 \* \* \* ~/aide/scripts/createLogs > ~/aide/logs/cron/cron\`date +\\\%s\`" 1>/dev/null; then
-  echo -e "   [\e[32mOK\e[0m] Cron is set up correctly."
+if [[ ${check} == 0 ]]; then
+	ok "No redundant databases."
+fi
+if crontab -l 2>/dev/null | grep "0 \*/3 \* \* \* ~/aide/scripts/createLogs > ~/aide/logs/cron/cron-\`date +\\\%s\`" 1>/dev/null; then
+	ok "Cron is set up correctly."
 else
-  echo -e "   [\e[31mERROR\e[0m] Cron error."
-  echo "   Updating cron..."
-  crontab -l 2>/dev/null | grep -v aide > /tmp/xxx
-  cat ${HOME_DIR}/scripts/cron >> /tmp/xxx
-  crontab /tmp/xxx
-  rm -f /tmp/xxx
-  echo -e "   [\e[32mOK\e[0m] Cron has been fixed."
+	if crontab ${HOME_DIR}/scripts/cron; then
+		ok "Cron has been set."
+	else
+		warrning "Failed to set up cron."
+	fi
 fi
